global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  repeat_interval: 1m
  routes:
  - match:
      alertname: telegrafReport
    receiver: default

receivers:
- name: default
  webhook_configs:
  - url: 'http://127.0.0.1:5000/newjson'
    send_resolved: false
    http_config:
      tls_config:
        insecure_skip_verify: true

