---
- include: install.yml

- include: startTelegrafService.yml
  when: installedSuccessfully == true

- include: addServetToPrometheus.yml
  when: metricsFired == true

- include: testSuite.yml
  when: nodeParsed == true
