---
- name: Start the Telegraf service
  service:
    name: telegraf
    state: started
    enabled: true

- name: Get Telegraf service status
  systemd:
    name: telegraf
    state: started
  register: telegraf_service_status

- name: metrics are fired variable
  set_fact:
    metricsFired: true



